# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-library-extension}
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["spanner"]
  s.date = %q{2010-09-14}
  s.description = %q{Combines paperclipped and taggable to create a general purpose faceted library}
  s.email = %q{will@spanner.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "app/models/library_page.rb",
     "app/views/admin/assets/_edit_metadata.html.haml",
     "app/views/admin/assets/_edit_title.html.haml",
     "app/views/admin/tags/_show_assets.html.haml",
     "cucumber.yml",
     "db/migrate/20091030115120_furniture.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/library/library_tag.rb",
     "lib/library/library_tags.rb",
     "lib/library/link_renderer.rb",
     "lib/library/more_asset_tags.rb",
     "lib/library/more_tag_tags.rb",
     "lib/library/site_controller.rb",
     "lib/library/tagged_asset.rb",
     "lib/tasks/library_extension_tasks.rake",
     "library_extension.rb",
     "pkg/radiant-library-extension-2.0.0.gem",
     "radiant-library-extension.gemspec",
     "spec/controllers/library_site_controller_spec.rb",
     "spec/datasets/library_pages_dataset.rb",
     "spec/datasets/library_sites_dataset.rb",
     "spec/datasets/library_tags_dataset.rb",
     "spec/models/library_page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/spanner/radiant-library-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Library Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/library_site_controller_spec.rb",
     "spec/datasets/library_pages_dataset.rb",
     "spec/datasets/library_sites_dataset.rb",
     "spec/datasets/library_tags_dataset.rb",
     "spec/models/library_page_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<radiant-taggable-extension>, [">= 1.2.0"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_dependency(%q<radiant-taggable-extension>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.0"])
    s.add_dependency(%q<radiant-taggable-extension>, [">= 1.2.0"])
  end
end

